### ISSUE TITLE
Error when using --bed argument

### ISSUE THREAD

**Issue by snoopy-448** [nygenome/lancet#25] opened 2018-07-12 13:01 UTC
Hi,
I can run LANCET with only --reg argument normally, but when I add the --bed argument, the software will stop immediately and throw out an error:
`terminate called after throwing an instance of 'std::invalid_argument'`
`  what():  stoi`
Below is my command using --reg only:
`lancet --tumor /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/bam_wes/P47T.dedupped.realigned.recal.bam --normal /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/bam_wes/P47N.dedupped.realigned.recal.bam --ref /home/ruibinxi_pkuhpc/lustre1/shiyang/reference_genomes/hg19_bwa/hg19.fa --reg chr22 --num-threads 1 > /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/lancet_result/P47T.vcf`
And this is my command using --bed:
`lancet --tumor /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/bam_wes/P47T.dedupped.realigned.recal.bam --normal /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/bam_wes/P47N.dedupped.realigned.recal.bam --ref /home/ruibinxi_pkuhpc/lustre1/shiyang/reference_genomes/hg19_bwa/hg19.fa --bed /home/ruibinxi_pkuhpc/lustre1/shiyang/reference_genomes/exome/SureSelect_All_Exon_V6_r2/S07604514_Covered.bed --num-threads 20 > /home/ruibinxi_pkuhpc/lustre1/shiyang/xiehe_icc/lancet_result/P47T.vcf`
Do you know the source of this error? I have also tried using --reg and --bed together, still failed.
By the way, there is a minor mistake in the tutorial, I think:
$NUMBER_OF_AUTOSOMES=22 should be NUMBER_OF_AUTOSOMES=22

Thanks a lot!
Yang

**Comment by gnarzisi** [comment] 2018-07-12 18:54
Thank you Yang for reporting the error and the typo in the tutorial.

Can you double check that the chromosome labels are consistent across all the files (BAM, BED, FASTA) ? I wonder if the problem is that the BAM uses chr22 while the BED only uses 22 for the same chromosome.

**Comment by snoopy-448** [comment] 2018-07-13 02:49
Oh I find where the problem is. The bed file I downloaded from Agilent have a header not in bed format:
```
>head S07604514_Covered.bed
browser position chr1:12081-12251
track name="Covered" description="Agilent SureSelect DNA - SureSelect Human All Exon V6 r2 - Genomic regions covered by probes" color=0,0,128
chr1	12080	12251	ref|DDX11L1,ref|NR_046018,ens|ENST00000518655,ens|ENST00000450305,ens|ENST00000456328,ens|ENST00000515242
chr1	12595	12802	ref|DDX11L1,ref|NR_046018,ens|ENST00000518655,ens|ENST00000450305,ens|ENST00000456328,ens|ENST00000515242
chr1	13163	13658	ref|DDX11L1,ref|NR_046018,ens|ENST00000518655,ens|ENST00000450305,ens|ENST00000456328,ens|ENST00000515242
chr1	14620	15015	ref|WASH7P,ref|NR_024540,ens|ENST00000538476,ens|ENST00000438504,ens|ENST00000488147,ens|ENST00000541675,ens|ENST00000423562
chr1	15795	15914	ref|WASH7P,ref|NR_024540,ens|ENST00000538476,ens|ENST00000438504,ens|ENST00000488147,ens|ENST00000541675,ens|ENST00000423562
chr1	16743	17098	ref|WASH7P,ref|NR_024540,ens|ENST00000438504,ens|ENST00000538476,ens|ENST00000488147,ens|ENST00000541675,ens|ENST00000423562
chr1	17247	18121	ref|WASH7P,ref|NR_024540,ens|ENST00000488147,ens|ENST00000438504,ens|ENST00000538476,ens|ENST00000541675,ens|ENST00000423562,miRNA|hsa-miR-6859-3p,miRNA|hsa-miR-6859-5p
chr1	18216	18411	ref|WASH7P,ref|NR_024540,ens|ENST00000488147,ens|ENST00000438504,ens|ENST00000538476,ens|ENST00000541675,ens|ENST00000423562

```
That error disappeareed after I removed the first two rows. Sorry for bothering you!

**Comment by gnarzisi** [comment] 2018-07-13 14:23
Great to hear the problem is resolved! Closing the ticket.

**Closed by gnarzisi** 2018-07-13 14:23 UTC
